version: 2
updates:
  # Maintain dependencies for Maven
  - package-ecosystem: "maven"
    open-pull-requests-limit: 5
    directory: "/tasks-manager"
    rebase-strategy: "auto"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "Thursday"
      timezone: "UTC"
      time: "03:00"
    groups:
      maven-deps:
        patterns:
          - "*"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    directory: "/.github"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "Thursday"
      timezone: "UTC"
      time: "03:00"
    groups:
      gh-actions:
        patterns:
          - "*"